import "./globals.css";
import { ViewTransition } from "react";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body 
      >
        <ViewTransition>
          {children}
        </ViewTransition>
      </body>
    </html>
  );
}
